image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - haskell.haskell
    - justusadam.language-haskell
    - anwar.papyrus-pdf

tasks:
  - name: Open the README
    command: open README.md
  - name: Build and run in GHCI
    init: stack build
    command: stack ghci
