image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - haskell.haskell
    - justusadam.language-haskell
    - tomoki1207.pdf

tasks:
  - name: Build and run in GHCI
    init: stack build
    command: stack ghci
