# thanks to https://github.com/rolandtritsch/haskell-aoc-2020

on: [push]

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        key: stack
        path: |
          ~/.stack
          ~/.stack-work
    - uses: actions/checkout@v4
    - name: Compile
      run: stack --system-ghc test --no-run-tests
    - name: Run tests
      run: stack --system-ghc test
    - name: Run benchmarks
      run: stack --system-ghc bench
  hlint:
    name: Hlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Hlint
      run: "curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s ."
